### ISSUE TITLE
URL class not recognised by static type checkers

### ISSUE THREAD

**Issue by TomHall2020** [brandonschabell/urlpath#2]
The urlpath.URL class for some reason is being classified as type `Any` by mypy and hence not being checked properly. I thought this might be a mypy bug, but the same issue occurs with pytype as well. 

Minimal example to demonstrate:
```
from pathlib import Path

from urlpath import URL

def do_something(path: Path, url: URL) -> str:

    return url / path

do_something(Path('file.ext'), URL('example.com')) # ok
do_something('file.ext', URL('example.com')) # error
do_something(Path('file.ext'), 'example.com') # ok ?!?

reveal_type(Path('file.ext')) # Revealed type is pathlib.Path
reveal_type(URL('example.com')) # Revealed type is "Any" ?!?
```

Any idea why this is? I just found this library today, already use pathlib a lot in my project and really like the look of this, but this behaviour is wierd and makes it less usable in a type hinted enviroment.

**Comment by brandonschabell** [comment]
@TomHall2020 I'm not very familiar with mypy. If you check the type of `URL('example.com')` in python, you will see that its type is the `urlpath.URL` class.

```python
>>> from urlpath import URL
>>> type(URL('example.com'))
<class 'urlpath.URL'>
```

I created a simple script:

```python
# script.py
from urlpath import URL


if __name__ == '__main__':
    print(URL('example.com'))
```

and checked it with pytype and I didn't receive any errors:
```bash
>>> pytype script.py

Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `.pytype'
[1/1] check script
Leaving directory '.pytype'
Success: no errors found
```

Let me know if you have any examples of this not working with Pytype and I'd be happy to reopen and investigate.

**Comment by TomHall2020** [comment]
Hi Brandon,

I've extended your simple example the minimal amount needed to produce the unexpected behaviour I'm getting:

```
from urlpath import URL

def example(url: URL) -> str:
    print(type(url))
    return url.stem


if __name__ == '__main__':
    example(URL('no_anchor'))
    example('text') #should raise pytype error as input is str not URL
```

On checking with pytype get a clean result when there should be an error:
```
>>> pytype script.py
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `.pytype'
[1/1] check script
Leaving directory '.pytype'
Success: no errors found
```

Attempting to run the script gives a runtime error due to the bad input on the last line:
```
>>> python script.py
<class 'urlpath.URL'>
<class 'str'>
Traceback (most recent call last):
  File "/Users/tomhall/dev/scratch/urlpath/script.py", line 10, in <module>
    example('text') #should raise type error as input is str not URL
  File "/Users/tomhall/dev/scratch/urlpath/script.py", line 5, in example
    return url.stem
AttributeError: 'str' object has no attribute 'stem'
```

Hopefully that shows the issue I'm having? In this example, if I replace the urlpath.URL with a pathlib.Path, then pytype correctly identifies the type error in the example script. 

I belive the issue is that for some reason although I can introspect the type of URL correctly as `urlpath.URL`, static type checkers are resolving it as type `Any`. I see the same behaviour in mypy which is why I suspect the issue is somehow related to urlpath rather than a bug in the typing packages.

**Comment by brandonschabell** [comment]
Hi @TomHall2020 , this appears to be a limitation in the `pytype` package: https://github.com/google/pytype/blob/main/docs/faq.md#how-do-i-get-type-information-for-third-party-libraries.
